project:
  type: website

website:
  title: "BDav"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bdav56
      - icon: twitter
        href: https://x.com/bdav56
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

