project:
  type: website
  output-dir: docs

website:
  title: "Branden Davenport's Blog on Science Fiction"
  navbar:
    right:
      - href: about.qmd
        text: About
      - href: index.qmd
        text: Posts
      - icon: github
        href: https://github.com/bdav56
      - icon: twitter
        href: https://x.com/bdav56
format:
  html:
    image: profile.jpg
    theme: [sandstone, styles.scss]

editor: visual

