project:
  type: website
  output-dir: docs

website:
  title: "BDav's Blog on Science Fiction"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bdav56
      - icon: twitter
        href: https://x.com/bdav56
format:
  html:
    image: profile.jpg
    theme: sandstone
    css: styles.css

editor: visual

